
name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip zip

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses

    - name: Install Build-Tools + AIDL
      run: |
        sdkmanager "build-tools;33.0.2"
        sdkmanager "platform-tools"
        sdkmanager "platforms;android-33"

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/*.apk
