name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install packages
      run: sudo apt-get update && sudo apt-get install -y unzip zip openjdk-11-jdk

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Cache Android SDK
      uses: actions/cache@v3
      with:
        path: ~/.android
        key: ${{ runner.os }}-android-sdk

    - name: Install Android SDK components
      run: |
        sdkmanager --update
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      run: buildozer android release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: bin/*.apk
